// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEAqQSw1C5dhun9cjQGxmH3PQ1QHwGnE',
    appId: '1:85888107965:web:2ad6c2efcef61600b7bed4',
    messagingSenderId: '85888107965',
    projectId: 'study-app-9d530',
    authDomain: 'study-app-9d530.firebaseapp.com',
    storageBucket: 'study-app-9d530.appspot.com',
    measurementId: 'G-6ZD4WZWDE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6BfJco2Tsml9_LJ7O4Vvbsw2OTNKqog',
    appId: '1:85888107965:android:aca53e93716437bdb7bed4',
    messagingSenderId: '85888107965',
    projectId: 'study-app-9d530',
    storageBucket: 'study-app-9d530.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwVSeigq6RwH_dezigNzix7lxN6Kz0f8',
    appId: '1:85888107965:ios:accd035bdd9a0fc2b7bed4',
    messagingSenderId: '85888107965',
    projectId: 'study-app-9d530',
    storageBucket: 'study-app-9d530.appspot.com',
    iosClientId: '85888107965-ggoobt5l6k4735a9q0tuk8dk26ahj7ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwVSeigq6RwH_dezigNzix7lxN6Kz0f8',
    appId: '1:85888107965:ios:accd035bdd9a0fc2b7bed4',
    messagingSenderId: '85888107965',
    projectId: 'study-app-9d530',
    storageBucket: 'study-app-9d530.appspot.com',
    iosClientId: '85888107965-ggoobt5l6k4735a9q0tuk8dk26ahj7ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );
}
